config/routes.rb
Rails.application.routes.draw do

  resources :lectures do
    collection do
      post 'create_comment', :action => 'create_comment'
      post 'new', :action => 'new'
      get 'new', :action => 'render_422'
    end

   member do
     put "like" => 'lectures#upvote'
     put "dislike" => 'lectures#downvote'
     put "spam" => 'lectures#set_spammed'
     put "unspam" => 'lectures#set_unspammed'
   end
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'homes#index'

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  has_many :comments

  mount_uploader :attachment, AttachmentUploader
  acts_as_votable

  validates :content, :presence =>true
  validates :title, :presence =>true
  validates :course_id, :presence =>true
  validates :user_id, :presence =>true

end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_lecture, only: [:show, :edit, :update, :destroy,:upvote, :downvote,:set_spammed, :set_unspammed ]
  before_action :verify_user, only: [:edit, :update, :destroy]

  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id = current_user.id
    respond_to do |format|
      if @lecture.save
        format.html { redirect_to lecture_path(@lecture) }
        format.json { render :show, status: :created, location: @lecture }
      end
    end
  end

  def index
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def new
    @lecture = Lecture.new
  end

  def render_422
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/422", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = 'Your comment was successfully added!'
      redirect_to lecture_url(@comment.lecture_id)
    end
  end


  def upvote
    @lecture.liked_by current_user
    redirect_to @lecture
  end

  def downvote
    @lecture.disliked_by current_user
    redirect_to @lecture
  end

  def set_spammed
    @lecture.liked_by current_user, :vote_scope => 'spam'
    redirect_to @lecture
  end

  def set_unspammed
    @lecture.unliked_by current_user, :vote_scope => 'spam'
    redirect_to @lecture
  end

  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_lecture
      @lecture = Lecture.find_by_id(params[:id])
    end

  def verify_user
    if @lecture.user.id != current_user.id
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/422", :layout => false, :status => :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end
  end

    def comment_params
      params.require(:comment).permit(:comment, :lecture_id, :user_id)
    end

    def lecture_params
      params.require(:lecture).permit(:title, :content, :attachment, :course_id, :user_id)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_comment.html.erb
<%= form_for(comment = Comment.new, :url => { :action => :create_comment }) do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="well">
      <h4>Leave a Comment:</h4>
      <div role="form">
        <div class="form-group">
          <%= f.text_area :comment, class: 'form-control', required: true, rows: '3' %>
        </div>
      </div>
      <%= hidden_field_tag 'comment[lecture_id]', params[:id] %>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/lectures/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
      <h1>New Lecture</h1>
      <hr>
      <%= form_for(@lecture, :url => { :action => :create }) do |f| %>
        <% if @lecture.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

            <ul>
            <% @lecture.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class:'form-control' %>
        </div>

        <div class="field form-group">
          <%= f.label :content %><br>
          <%= f.cktext_area :content, :width => 100, class:'form-control', :height => 80 %>
        </div>

          <br>

        <div class="form-group">
          <%= f.label :attachment %>
          <br>
          <p class="help-block">Upload attachment.</p>
          <%= f.file_field :attachment %>
          <br>
        </div>

        <%= hidden_field_tag 'lecture[course_id]', params[:c_id]  if params[:c_id] != nil%>

        <div class="actions">
          <%= f.submit class:'btn btn-primary btn-block' %>
        </div>
      <% end %>
      <hr>
      <%= link_to 'Back', courses_url, style: 'font-size: 1.5em;' %>
    </div>
  </div>
</div>

app/views/lectures/edit.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
    <h1>Editing Lecture</h1>
    <hr>
    <%= form_for(@lecture) do |f| %>
        <% if @lecture.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

              <ul>
                <% @lecture.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class:'form-control' %>
        </div>

        <div class="field form-group">
          <%= f.label :content %><br>
          <%= f.cktext_area :content, :width => 100, class:'form-control', :height => 80 %>
        </div>

        <br>

        <div class="form-group">
          <%= f.label :attachment %>
          <br>
          <p class="help-block">Upload attachment.</p>
          <%= f.file_field :attachment %>
          <br>
        </div>

        <%= hidden_field_tag 'lecture[course_id]', params[:c_id]  if params[:c_id] != nil%>

        <div class="actions">
          <%= f.submit class:'btn btn-primary btn-block' %>
        </div>
    <% end %>
    <hr>
  </div>
</div>
</div>

app/views/lectures/new.html.erb
<%= render 'form' %>

app/views/lectures/show.html.erb
<div class="container">
  <div class="row">
    <!-- Blog Post Content Column -->
    <div class="post col-xs-offset-1 col-xs-10 col-xs-offset-1">
      <!-- Blog Post -->
      <h1><%= link_to @lecture.try(:course).try(:title), course_path(@lecture.course_id), style: 'text-decoration: none;' %></h1>
      <!-- Title -->
      <div id="post_title">
        <h2><%= @lecture.try(:title)%></h2>
      </div>

      <!-- Author -->
      <p class="lead">
        by <a><%= @lecture.user.name %></a>
      </p>

      <% if @lecture.user.id === current_user.id %>
      <p>
        <%= link_to '<span class="glyphicon glyphicon-remove"></span> Delete'.html_safe, @lecture, class: 'btn btn-danger',method: :delete, data: { confirm: 'Are you sure?' } %>
        <span>  </span>
        <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, edit_lecture_url(@lecture), class: 'btn btn-success', data: { no_turbolink: true }  %>
      </p>
      <% end %>

      <hr>

      <!-- Post Content -->
      <div id="post_desc" class="container-fluid">
        <p class="lead"><%= @lecture.content.html_safe %></p>
      </div>

      <hr>

      <div>
        <h4>Was this helpful?</h4>
        <%= link_to like_lecture_path(@lecture), class: 'like', method: :put do %>
          <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center"></span>
          <span class="badge"><%= @lecture.get_upvotes.size %></span>
        <% end %>

        <%= link_to dislike_lecture_path(@lecture), class: 'dislike', method: :put do %>
            <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center"></span>
            <span class="badge"><%= @lecture.get_downvotes.size %></span>
        <% end %>

        <h4>Report as a spam?</h4>

        <% if current_user.voted_on?(@lecture,:vote_scope => 'spam') %>
            <%= link_to unspam_lecture_path(@lecture), class: 'dislike', method: :put do %>
                <span class="glyphicon glyphicon-ban-circle glyphicon-align-center"></span>
                <span class="badge">Reported as a spam</span>
            <% end %>
        <% else %>
            <%= link_to spam_lecture_path(@lecture), class: 'like', method: :put do %>
                <span class="glyphicon glyphicon-ban-circle glyphicon-align-center"></span>
            <% end %>
        <% end %>
      </div>

      <% if @lecture.attachment.file != nil %>
          <hr>
          <br>
          <p class="lead">Download attachment:</p>
        <% file = '<i class="glyphicon glyphicon-paperclip"></i> '+@lecture.attachment.file.basename %>
        <%= link_to file.html_safe, @lecture.attachment.url, id: 'attach' %>
      <% end %>

      <hr>

      <!-- Blog Comments -->

      <!-- Posted Comments -->
      <!-- Comment -->
      <h3>Comments: </h3>
      <div id="comments_section" class="container-fluid">
        <% @lecture.comments.each do |comment| %>
        <div class="comment media">
          <a class="pull-left" href="#">
            <% if comment.user.image.file != nil %>
                <%= image_tag comment.user.image.url, class:'img img-circle', size: "64x64" %>
            <% else %>
                <img class="media-object" src="http://placehold.it/64x64" alt="">
            <% end %>
          </a>
          <div class="media-body">
            <h4 class="media-heading"><%= comment.user.name %>
              <small><%= time_ago_in_words(comment.created_at) %></small>
            </h4><blockquote class="comment_value"><%= comment.comment %></blockquote></div>
        </div>
        <% end %>
      </div>
      
      <br>
      <!-- Comments Form -->
      <hr>

      <%=render 'comment' %>

    </div>
  </div>
</div>