config/routes.rb
Rails.application.routes.draw do

  resources :lectures do
    collection do
      post 'create_comment', :action => 'create_comment'
      post 'new', :action => 'new'
      get 'new', :action => 'render_422'
    end

   member do
     put "like" => 'lectures#upvote'
     put "dislike" => 'lectures#downvote'
     put "spam" => 'lectures#set_spammed'
     put "unspam" => 'lectures#set_unspammed'
   end
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'homes#index'

end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :verify_role, only: [:new]
  before_action :verify_user, only: [:edit, :update, :destroy]

  # GET /courses/1/edit
  #def edit
    #Check if the user session equal to the user_id of the course
  #end

  def index
    #@courses = Course.all
    @courses = Course.page(params[:page]).per(8)
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def verify_user
    if @course.user.id != current_user.id
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/422", :layout => false, :status => :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end
  end

  def verify_role
    if current_user.status != "instructor"
      respond_to do |format|
        format.html { render :file => "#{Rails.root}/public/422", :layout => false, :status => :not_found }
        format.xml  { head :not_found }
        format.any  { head :not_found }
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find_by_id(params[:id])
    if @course == nil
        render :file => "#{Rails.root}/public/404"
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :user_id, :description, :image)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
      <h1>New Course</h1>
      <hr>
      <%= form_for(@course) do |f| %>
          <% if @course.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

                <ul>
                  <% @course.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, class:'form-control' %>
          </div>

          <div class="field form-group">
            <%= f.label :description %><br>
            <%= f.text_area :description, class:'form-control', rows:'5' %>
          </div>

          <div class="form-group">
            <%= f.label :image %><br>
            <%= f.file_field :image %>
          </div>

          <div class="actions">
            <%= f.submit class:'btn btn-primary btn-block' %>
          </div>
      <% end %>
      <hr>
      <%= link_to 'Back', courses_path, style: 'font-size: 1.5em;' %>

    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="text-center">Courses</h1>
  </div>
  <p class="lead text-center">"The Expert in Everything was once a beginner" by Helen Hayes</p>
  <div class="container">
    <div class="row stylish-panel">
      <% @courses.each do |course| %>
        <div class="col-md-3">
          <div>
            <% if course.image.file != nil %>
                <%= image_tag course.image.url, class:'img img-circle', size: "200x200"%>
            <% else %>
                <img class="media-object img img-circle" src="http://lorempixel.com/200/200/abstract/2/" alt="">
            <% end %>
            <h2><%= course.title %></h2>
            <p>By: <%= link_to course.user.name %></p>
            <%= link_to 'View Course', course, class: 'btn btn-default' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
  <div align="center">
    <%= paginate @courses %>
    <br>
    <%= page_entries_info @courses %>
  </div>
</div>
<!-- /container -->

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<div class="container" style="margin-top: 25px">
  <% if user_signed_in? %>
      <%if current_user.status === "instructor" && current_user.id === @course.user.id  %>

          <%= link_to '<i class="glyphicon glyphicon-edit"></i> Edit Course '.html_safe, edit_course_path(@course), class: 'btn btn-warning btn-md' %>
          <span>  </span>
          <%= link_to '<i class="glyphicon glyphicon-remove"></i> Delete Course '.html_safe, @course ,method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-md' %>
      <% end %>
  <% end %>
  <div class="page-header page-heading">
    <h1 class="pull-left"><%= @course.title %></h1>
    <div class="clearfix">
    </div>
  </div>
  <p class="lead"><%= @course.try(:description) %></p>
  <table class="table forum table-striped">
    <thead>
    <tr>
      <th class="cell-stat"></th>
      <th>
        <h3>Lectures</h3>
      </th>
      <th class="cell-stat text-center hidden-xs hidden-sm">Likes</th>
      <th class="cell-stat text-center hidden-xs hidden-sm">Comments</th>
      <th class="cell-stat-2x hidden-xs hidden-sm">Last Comment</th>
    </tr>
    </thead>
    <tbody>
    <% @course.lectures.each do |lecture| %>
    <tr>
      <td class="text-center"><i class="fa fa-question fa-2x text-primary"></i></td>
      <td>
        <h4> <%= link_to lecture.title, lecture %> <br><small>Some description</small></h4>
      </td>
      <td class="text-center hidden-xs hidden-sm"><a><%= lecture.get_upvotes.size %></a></td>
      <td class="text-center hidden-xs hidden-sm"><a><%= lecture.comments.size %></a></td>
      <td class="hidden-xs hidden-sm"><%= 'by' if lecture.comments.size != 0 %> <%= link_to lecture.comments.last.user.name if lecture.comments.size != 0 %><br><small><i class="fa fa-clock-o"></i><%= time_ago_in_words(lecture.comments.last.created_at)+" ago" if lecture.comments.size != 0 %></small></td>
    </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <% if user_signed_in? %>
      <%if current_user.status === "instructor" && current_user.id === @course.user.id  %>
          <div class="row">
            <div class="col-xs-offset-4 col-xs-4 col-xs-offset-4">
              <%= link_to '<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add a new Lecture '.html_safe, new_lecture_path(:c_id => @course.id), method: :post, class: 'btn btn-success btn-lg btn-block' %>
            </div>
          </div>
      <% end %>
  <% end %>

</div>
</div>